---
title: "R Notebook"
output: html_notebook
---

Read in the data:

```{r}
table6a <- read.table(file = "Table6a_Highest_education_NonCTE_concentrators.csv", 
               sep=",",
               header = TRUE,
               encoding="UTF-8", 
               col.names = c("characteristic2","pctNonCTEdistribution"))

```


Convert value column to percentages:

```{r}
table6a$pctNonCTEdistribution <- table6a$pctNonCTEdistribution*100
table6a
```


Pie chart variables:

```{r}
pie_values <- table6a$pctNonCTEdistribution
pie_labels <- table6a$characteristic2
pie_colors <- rainbow(length(pie_values))

title_text <- "Percentage distribution of high school non-CTE concentrators by highest level of\neducational attainment eight years after expected high school graduation"
```


Make a pie chart:

```{r, fig.height = 5, fig.width = 7}
par(mai=c(0.2,0.2,0.2,0.2), lwd=2)

pie(pie_values, labels = paste0(pie_values,"%"), col = pie_colors,
    radius = .55, cex = .9,
    clockwise = TRUE)

title(main = title_text, cex.main = 1, line = -1.75)

legend(x = -1.3, y = -.75, legend = pie_labels, fill = pie_colors, 
      cex = .75, bty = 'n', ncol = 2)
```


Save the plot:

```{r}
pdf("practice_piechart_key.pdf", width=6, height=4)

par(mai=c(0.2,0.2,0.2,0.2), lwd=2)

pie(pie_values, labels = paste0(pie_values,"%"), col = pie_colors,
    radius = .55, cex = .9,
    clockwise = TRUE)

title(main = title_text, cex.main = 1, line = -1.75)

legend(x = -1.3, y = -.75, legend = pie_labels, fill = pie_colors, 
      cex = .75, bty = 'n', ncol = 2)

dev.off()
```


